// export const LOGIN = 'LOGIN'

export const LOAD_TOKEN = 'LOAD_TOKEN'
export const LOAD_TOKEN_SUCCESS = 'LOAD_TOKEN_SUCCESS'
export const LOAD_TOKEN_ERROR = 'LOAD_TOKEN_ERROR'

export const LOAD_GET_USER = 'LOAD_GET_USER'
export const LOAD_GET_USER_SUCCESS = 'LOAD_GET_USER_SUCCESS'
export const LOAD_GET_USER_ERROR = 'LOAD_GET_USER_ERROR'

export const LOGOUT = 'LOGOUT'

export const LOAD_EDIT_USER = 'LOAD_EDIT_USER'
export const LOAD_EDIT_USER_SUCCESS = 'LOAD_EDIT_USER_SUCCESS'
export const LOAD_EDIT_USER_ERROR = 'LOAD_EDIT_USER_ERROR'


// export const GET_USER = 'GET_USER'

// export const EDIT_USER = 'EDIT_USER'
